version: 2

# registries:
#  github-mvn:
#    type: maven-repository
#    url: https://maven.pkg.github.com/evoja/java-commons
#    username: patuser
#    password: ${{secrets.DEPS_GHPKG_R_PAT}}

updates:

  - package-ecosystem: github-actions
    directory: /
    target-branch: deps/gha-maj
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: '**'
        update-types:
          - 'version-update:semver-minor'
          - 'version-update:semver-patch'

  - package-ecosystem: github-actions
    directory: /
    target-branch: deps/gha-min
    schedule:
      interval: daily
    open-pull-requests-limit: 3
    ignore:
      - dependency-name: '**'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-patch'

  - package-ecosystem: maven
    directory: /
    target-branch: deps/mvn-maj
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: '**'
        update-types:
          - 'version-update:semver-minor'
          - 'version-update:semver-patch'

  - package-ecosystem: maven
    directory: /
    target-branch: deps/mvn-min
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: '**'
        update-types:
          - 'version-update:semver-major'
          - 'version-update:semver-patch'

  - package-ecosystem: npm
    directory: /.github/evj-tools
    target-branch: deps/npm
    schedule:
      interval: daily
    open-pull-requests-limit: 5
