name: Dependaboja
description: Merge dependabot PRs and sync aggregated branches with master

inputs:
  disabled_pr_targets:
    description: Comma separated list of branches wich are not allowed to be a PR target for auto merge. Default is 'master,main'
    required: false
    default: master,main
  sync_with:
    description: Comma separated list of branches which should be merged to agregated dependency branches automatically. Default is 'master,main'
    required: false
    default: master,main
  fetch_depth:
    description: We need a deep fetch in order to merge
    required: false
    default: master,main


outputs: {}
  # random-number:
  #   description: "Random number"
  #   value: ${{ steps.random-number-generator.outputs.random-id }}

runs:
  using: composite
  steps:
    - name: Run on PR
      if: ${{ github.event_name == 'pull_request' }}
      shell: bash
      run: echo this was a pull request!

    - name: Run on push
      if: ${{ github.event_name == 'push' }}
      shell: bash
      run: echo this was a push!

    - name: Is it a branch to sync?
      id: shouldsync
      if: ${{ github.event_name == 'push' }}
      shell: bash
      run: |
        STR="${{inputs.sync_with}}"
        readarray -d , -t ARR <<< "$STR"
        for word in "${ARR[@]}"; do
          echo $word
          if [ $word == "${{github.ref_name}}" ]; then
            echo "::set-output name=shouldsync::1"
          fi
        done

    - name: Show YQ version or try to install
      if: ${{steps.shouldsync.outputs.shouldsync == 1}}
      shell: bash
      run: |
        jq --version || echo "no-jq"
        yq --version || (echo "no-yq" && pip3 install yq)

    - name: Find dependabot config
      id: find_dependabot
      if: ${{steps.shouldsync.outputs.shouldsync == 1}}
      shell: bash
      run: |
        if [ -f ./.github/dependabot.yaml ]; then
          echo "::set-output name=ext::yaml"
        elif [ -f ./.github/dependabot.yml ]; then
          echo "::set-output name=ext::yml"
        else
          echo "Cannot find dependabot config"
          exit 1
        fi

    - name: Read dependabot config
      if: ${{steps.shouldsync.outputs.shouldsync == 1}}
      shell: bash
      run: |
        DEPCONF=./.github/dependabot.${{steps.find_dependabot.outputs.ext}}
        TARGETS=($(yq e '.updates[].["target-branch"]' $DEPCONF))
        for REF in "${TARGETS[@]}"; do
          echo ALALA $REF
        done

    - name: Report skip branch
      if: ${{steps.shouldsync.outputs.shouldsync != 1}}
      shell: bash
      run: echo "Skip this branch"
