name: Check that Java project is buildable
on:
  workflow_call:
    inputs:
      path_to_java:
        description: A path where the java project is located
        default: '.'
        type: string
      path_to_mvn_settings:
        description: A path to maven settings.xml
        default: .github/workflows/mvn-settings.xml
        type: string
      path_to_mvn_output:
        description: A path where the java packages are installed
        default: ~/.m2/repository/net/evoja
        type: string
    secrets:
      GHCR_R_PAT:
        description: A token that can read from GitHub packages

permissions:
  packages: none

env:
  src_tpl: ${{ format('{0}/*/src/**', inputs.path_to_java) }}
  poms_tpl: ${{ format('{0}/**/pom.xml', inputs.path_to_java) }}
  pom_tpl: ${{ format('{0}/pom.xml', inputs.path_to_java) }}

jobs:

  checkingstamps:
    name: Checking stamps
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.4.0

      - name: Calc hash of java project files
        id: javahash
        env:
          JAVA_HASH: ${{ hashFiles(env.src_tpl, env.poms_tpl, env.pom_tpl) }}
        run: |
          echo "::set-output name=javahash::$JAVA_HASH"

      - name: Use cache
        id: cache
        uses: actions/cache@v2.1.6 # originally pointed to c64c572235d810460d0d6876e9c705ad5002b353
        with:
          # add `run_attempt` in order to never use cached key
          key: checkingstamps-check-${{github.run_id}}-${{github.run_attempt}}
          restore-keys: |
            checkingstamps-all-${{steps.javahash.outputs.javahash}}
            checkingstamps-all-
            checkingstamps-one-
          path: |
            ~/evj-checkingstamps

      - name: Check stamps
        id: checkstamps
        env:
          JAVA_HASH: ${{steps.javahash.outputs.javahash}}
        run: |
          if [ -f "~/evj-checkingstamps/all-$JAVA_HASH.txt" ]; then
            echo "::set-output name=checked::1"
          fi;
    outputs:
      checked: ${{steps.checkstamps.outputs.checked}}
      javahash: ${{steps.javahash.outputs.javahash}}

  report-checked-before:
    needs: [checkingstamps]
    name: Report that Java build is skipped
    if: ${{needs.checkingstamps.outputs.checked == 1}}
    runs-on: ubuntu-latest
    steps:
      - name: Report
        run: |
          echo "Java build is skipped because the same source was checked before."


  build-java:
    name: Build and test java project
    needs: [checkingstamps]
    if: ${{needs.checkingstamps.outputs.checked != 1}}
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.4.0

      - uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Use cache for checking stamps
        id: cache-checkingstamps
        uses: actions/cache@v2.1.7
        with:
          key: checkingstamps-all-${{needs.checkingstamps.outputs.javahash}}
          restore-keys: |
            checkingstamps-all-
            checkingstamps-one-
          path: |
            ~/evj-checkingstamps

      - name: Use cache for maven dependencies
        id: cache
        uses: actions/cache@v2.1.7
        with:
          key: mvndeps-all-${{ hashFiles(env.poms_tpl) }}-${{ hashFiles(env.pom_tpl)}}
          restore-keys: |
            mvndeps-all-${{ hashFiles(env.poms_tpl) }}
            mvndeps-all-
            mvndeps-one-
            mvndeps-
          path: |
            ~/.m2/repository

      - name: Show Maven and Java versions
        run: |
          echo "### Java"
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
          printf "\n### Maven\n"
          mvn --version

      - name: Auth to GitHub Maven
        env:
          MVN_SETTINGS: ${{inputs.path_to_mvn_settings}}
        run: |
          if [ -f "$MVN_SETTINGS" ]; then
            cp "$MVN_SETTINGS" ~/.m2/settings.xml
          fi

      - name: Build all java subprojects
        env:
          PROJ: ${{inputs.path_to_java}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHCR_R_PAT: ${{ secrets.GHCR_R_PAT }}
        run: |
          cd "$PROJ"
          mvn --batch-mode install

      - name: Print test reports
        env:
          PROJ: ${{inputs.path_to_java}}
        run: |
          cd "$PROJ"
          find . -type d  -name surefire-reports -exec sh -c "echo "==============================================================================="  && echo {} && cat {}/*.txt" \;

      - name: Write success stamps
        env:
          JAVA_HASH: ${{needs.checkingstamps.outputs.javahash}}
        run: |
          mkdir -p ~/evj-checkingstamps
          touch "~/evj-checkingstamps/all-$JAVA_HASH.txt"

      - name: Delete our jars before caching maven dependencies
        env:
          MVN_OUTPUT: ${{inputs.path_to_mvn_output}}
        run: |
          rm -rf "$MVN_OUTPUT"
