name: Test
on:
  push:
    branches:
      - '**'
      - '!dependabot/**'

permissions:
  packages: none

jobs:

  editorconfig-checker:
    name: ec
    uses: evoja/java-commons/.github/workflows/editorconfig-checker.yaml@760f418e9159427adcf61cc296ca89b613429597 # same as @wf/editorconfig-checker/01

  ca-java:
    name: caj
    uses: evoja/java-commons/.github/workflows/ca-java.yaml@93521b41fb356a7cdd7aeb16bf7eaf0222edfa1a # same as @wf/ca-java/00
