name: Test
on:
  push:
    branches:
      - '**'
  workflow_call: {}

#env:
#  MVN_EVJ_PATH: ~/.m2/repository/net/evoja

jobs:
  editorconfig-checker:
    name: Check editorcofnig
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Show Node and NPM versions
        run: |
          echo node@$(node --version)
          echo npm@$(npm --version)

      - name: Install NPM dependencies
        run: |
          cd .github/evj-tools
          npm ci

      - name: Check editorconfig
        run: |
          cd .github/evj-tools
          npm run check-editorconfig

      - name: Check for tabs in a middle of a line
        run: |
          find . -type f \
              -not -name '*.iml' \
              -not -name '*.png' \
              -not -path '**/node_modules/**' \
              -not -path '**/target/**' \
              -not -path '**/.idea/**' \
              -not -path './.git/**' \
              -exec grep -HnE $'[^/-]\S\t+' {} \; \
            | grep . && printf '\033[0m' && exit 1 || printf '\033[0m'


  build-java:
    name: Build and test java project
    runs-on: ubuntu-latest
    env:
      IMAGE_PUSH: >-
        ${{
          startsWith(github.ref, 'refs/tags/java-commons-dev/')
        }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Use cache
        id: cache
        uses: actions/cache@v2
        with:
          key: mvndeps-all-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvndeps-all-
            mvndeps-one-
            mvndeps-
          path: |
            ~/.m2/repository

      - name: Show Maven and Java versions
        run: |
          echo "### Java"
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
          printf "\n### Maven\n"
          mvn --version

      - name: Build all java subprojects
        run: |
          mvn --batch-mode install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print test reports
        run: |
          find . -type d  -name surefire-reports -exec sh -c "echo "==============================================================================="  && echo {} && cat {}/*.txt" \;

      - name: Delete our jars before caching maven dependencies
        run: |
          rm -rf ~/.m2/repository/net/evoja
