name: Test
on:
  push:
    branches:
      - '**'
  workflow_call: {}

#env:
#  MVN_EVJ_PATH: ~/.m2/repository/net/evoja

jobs:

  editorconfig-checker:
    name: EC
    uses: evoja/java-commons/.github/workflows/editorconfig-checker.yaml@13541445ad45110480842df586da06b72d13b15f # same as @wf/editorconfig-checker/00

  checkingstamps:
    name: Checking stamps
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Calc hash of java project files
        id: javahash
        run: |
          echo "::set-output name=javahash::${{ hashFiles('*/src/**', '**/pom.xml', 'pom.xml') }}"

      - name: Use cache
        id: cache
        uses: actions/cache@v2
        with:
          # add `run_attempt` in order to never use cached key
          key: checkingstamps-check-${{github.run_id}}-${{github.run_attempt}}
          restore-keys: |
            checkingstamps-all-${{steps.javahash.outputs.javahash}}
            checkingstamps-all-
            checkingstamps-one-
          path: |
            ~/evj-checkingstamps

      - name: Check stamps
        id: checkstamps
        run: |
          if [ -f ~/evj-checkingstamps/all-${{steps.javahash.outputs.javahash}}.txt ]; then
            echo "::set-output name=checked::1"
          fi;
    outputs:
      checked: ${{steps.checkstamps.outputs.checked}}
      javahash: ${{steps.javahash.outputs.javahash}}

  report-checked-before:
    needs: [checkingstamps]
    name: Report that Java build is skipped
    if: ${{needs.checkingstamps.outputs.checked == 1}}
    runs-on: ubuntu-latest
    steps:
      - name: Report
        run: |
          echo "Java build is skipped because the same source was checked before."


  build-java:
    name: Build and test java project
    needs: [checkingstamps]
    if: ${{needs.checkingstamps.outputs.checked != 1}}
    runs-on: ubuntu-latest
    env:
      IMAGE_PUSH: >-
        ${{
          startsWith(github.ref, 'refs/tags/java-commons-dev/')
        }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Use cache
        id: cache-checkingstamps
        uses: actions/cache@v2
        with:
          key: checkingstamps-all-${{needs.checkingstamps.outputs.javahash}}
          restore-keys: |
            checkingstamps-all-
            checkingstamps-one-
          path: |
            ~/evj-checkingstamps

      - name: Use cache
        id: cache
        uses: actions/cache@v2
        with:
          key: mvndeps-all-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            mvndeps-all-
            mvndeps-one-
            mvndeps-
          path: |
            ~/.m2/repository

      - name: Show Maven and Java versions
        run: |
          echo "### Java"
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
          printf "\n### Maven\n"
          mvn --version

      - name: Build all java subprojects
        run: |
          mvn --batch-mode install
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print test reports
        run: |
          find . -type d  -name surefire-reports -exec sh -c "echo "==============================================================================="  && echo {} && cat {}/*.txt" \;

      - name: Write success stamps
        run: |
          mkdir -p ~/evj-checkingstamps
          touch ~/evj-checkingstamps/all-${{needs.checkingstamps.outputs.javahash}}.txt

      - name: Delete our jars before caching maven dependencies
        run: |
          rm -rf ~/.m2/repository/net/evoja
