name: Test
on:
  push:
    branches:
      - '**'
  workflow_call:
    inputs:
      path_to_java:
        description: A path where the java project is located
        default: '.'
        type: string
      path_to_mvn_settings:
        description: A path to maven settings.xml
        default: .github/workflows/mvn-settings.xml
        type: string
      path_to_mvn_output:
        description: A path where the java packages are installed
        default: ~/.m2/repository/net/evoja
        type: string
    secrets:
      GHCR_R_PAT:
        description: A token that can read from GitHub packages

jobs:

  editorconfig-checker:
    name: ec
    uses: evoja/java-commons/.github/workflows/editorconfig-checker.yaml@13541445ad45110480842df586da06b72d13b15f # same as @wf/editorconfig-checker/00

  ca-java:
    name: caj
    uses: evoja/java-commons/.github/workflows/ca-java.yaml@93521b41fb356a7cdd7aeb16bf7eaf0222edfa1a # same as @wf/ca-java/00
    with:
      path_to_java: ${{inputs.path_to_java}}
      path_to_mvn_settings: ${{inputs.path_to_mvn_settings}}
      path_to_mvn_output: ${{inputs.path_to_mvn_output}}
    secrets:
      GHCR_R_PAT: ${{secrets.GHCR_R_PAT}}
