name: Test
on:
  push:
    branches:
      - '**'
      - '!dependabot/**'

permissions:
  contents: read

jobs:

  editorconfig-checker:
    name: ec
    uses: evoja/java-commons/.github/workflows/editorconfig-checker.yaml@5c9da1c159dc3a0dc1d4e07a2d3ddc28b8c28ed9 # same as @wf/editorconfig-checker/04

  ca-java:
    name: caj
    uses: evoja/java-commons/.github/workflows/ca-java.yaml@5c9da1c159dc3a0dc1d4e07a2d3ddc28b8c28ed9 # same as @wf/ca-java/03
    with:
      java_version: '11'
