name: dependaboja

on:
  push:
    branches:
      - master
  pull_request:
    branches: [deps/**]
    types: [opened, synchronize, reopened]

permissions:
  pull-requests: write
  contents: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2.4.0
      - name: Dependaboja
        uses: evoja/dependaboja@b5a230e6c445451aa392f404d842093965b6cffa
