name: Deploy to registry
on:
  workflow_call:
    inputs:
      path_to_java:
        description: A path where the java project is located
        default: '.'
        type: string
      root_proj_name:
        description: name of the root project that is located in `path_to_java`
        default: commons
        type: string
      path_to_mvn_settings:
        description: A path to maven settings.xml
        default: .github/workflows/mvn-settings.xml
        type: string
      path_to_mvn_output:
        description: A path where the java packages are installed
        default: ~/.m2/repository/net/evoja
        type: string
    secrets:
      GHCR_R_PAT:
        description: A token that can read from GitHub packages

env:
  src_tpl: ${{ format('{0}/*/src/**', inputs.path_to_java) }}
  poms_tpl: ${{ format('{0}/**/pom.xml', inputs.path_to_java) }}
  pom_tpl: ${{ format('{0}/pom.xml', inputs.path_to_java) }}


jobs:
  attributes:
    name: Check module name and version
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Verify module
        id: proj
        run: |
          PROJ=$(echo '${{github.ref}}' | \
            sed -E 's|^refs/tags/([^/]*)/.*|\1|')
          if [ $PROJ == ${{inputs.root_proj_name}} ]; then
            PROJ_PATH=${{inputs.path_to_java}}
          else
            PROJ_PATH="${{inputs.path_to_java}}/$PROJ"
          fi;
          echo "PROJ_PATH=$PROJ_PATH"
          [ -d $PROJ_PATH ]
          echo "::set-output name=path::$PROJ_PATH"

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Auth to GitHub Maven
        run: |
          if [ -f ${{inputs.path_to_mvn_settings}} ]; then
            cp ${{inputs.path_to_mvn_settings}} ~/.m2/settings.xml
          fi

      - name: Verify version
        run: |
          cd ${{steps.proj.outputs.path}}
          VER=$(echo '${{github.ref}}' | \
            sed -E 's|^refs/tags/[^/]*/(.*)|\1|' | \
            sed -E 's|/|.|g')
          echo "VER=$VER"
          MVN_VER=$(mvn help:evaluate -Dexpression=project.version -pl . --non-recursive -q -DforceStdout)
          echo "MVN_VER=$MVN_VER"
          [ $VER == $MVN_VER ]
#          echo "VER=$VER" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHCR_R_PAT: ${{ secrets.GHCR_R_PAT }}

    outputs:
      path: ${{steps.proj.outputs.path}}


  editorconfig-checker:
    name: ec
    uses: evoja/java-commons/.github/workflows/editorconfig-checker.yaml@13541445ad45110480842df586da06b72d13b15f # same as @wf/editorconfig-checker/00

  ca-java:
    name: caj
    uses: evoja/java-commons/.github/workflows/ca-java.yaml@93521b41fb356a7cdd7aeb16bf7eaf0222edfa1a # same as @wf/ca-java/00
    with:
      path_to_java: ${{inputs.path_to_java}}
      path_to_mvn_settings: ${{inputs.path_to_mvn_settings}}
      path_to_mvn_output: ${{inputs.path_to_mvn_output}}
    secrets:
      GHCR_R_PAT: ${{secrets.GHCR_R_PAT}}


  deploy:
    needs: [attributes, editorconfig-checker, ca-java]
    runs-on: ubuntu-latest
    env:
      PROJ_PATH: ${{needs.attributes.outputs.path}}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Use cache
        id: cache
        uses: actions/cache@v2
        with:
          key: mvndeps-one-${{hashFiles(format('{0}/pom.xml', env.PROJ_PATH))}}
          restore-keys: |
            mvndeps-all-${{ hashFiles(env.poms_tpl) }}-${{ hashFiles(env.pom_tpl)}}
            mvndeps-all-${{ hashFiles(env.poms_tpl) }}
            mvndeps-all-
            mvndeps-one-
            mvndeps-
          path: |
            ~/.m2/repository

      - name: Show Maven and Java versions
        run: |
          echo "### Java"
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
          printf "\n### Maven\n"
          mvn --version

      - name: Auth to GitHub Maven
        run: |
          if [ -f ${{inputs.path_to_mvn_settings}} ]; then
            cp ${{inputs.path_to_mvn_settings}} ~/.m2/settings.xml
          fi

      - name: Build and deploy
        run: |
          cd $PROJ_PATH
          mvn --batch-mode deploy -P purity-strict -pl .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHCR_R_PAT: ${{ secrets.GHCR_R_PAT }}

      - name: Print test reports
        run: |
          cd $PROJ_PATH
          find . -type d  -name surefire-reports -exec sh -c "echo "==============================================================================="  && echo {} && cat {}/*.txt" \;

      - name: Delete our jars before caching maven dependencies
        run: |
          rm -rf ${{inputs.path_to_mvn_output}}
