name: Check editorconfig
on:
  workflow_call:
    inputs:
      checker_version:
        description: Version of `editorconfig-checker`
        default: 4.0.2
        type: string

permissions:
  packages: none

jobs:

  editorconfig-checker:
    name: Check editorconfig
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Check editorconfig
        uses: editorconfig-checker/action-editorconfig-checker@0527b11555ed46afd00df746f35b79cb7f7b68c2 # refs/tags/v1.0.0

      - name: Check for tabs in a middle of a line
        run: |
          find . -type f \
              -not -name '*.iml' \
              -not -name '*.png' \
              -not -path '**/node_modules/**' \
              -not -path '**/target/**' \
              -not -path '**/.idea/**' \
              -not -path './.git/**' \
              -exec grep -HnE $'[^/-]\S\t+' {} \; \
            | grep . && printf '\033[0m' && exit 1 || printf '\033[0m'

