name: Check module name and version
on:
  workflow_call:
    inputs:
      path_to_java:
        description: A path where the java project is located
        default: '.'
        type: string
      root_proj_name:
        description: name of the root project that is located in `path_to_java`
        default: commons
        type: string
      path_to_mvn_settings:
        description: A path to maven settings.xml
        default: .github/workflows/mvn-settings.xml
        type: string
    secrets:
      GHCR_R_PAT:
        description: A token that can read from GitHub packages
    outputs:
      path:
        value: ${{jobs.attributes.outputs.path}}

permissions:
  contents: read

jobs:
  attributes:
    name: Check module name and version
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2.4.0

      - name: Verify module
        id: proj
        env:
          REF: ${{github.ref}}
          ROOT_PROJ_NAME: ${{inputs.root_proj_name}}
          PATH_TO_JAVA: ${{inputs.path_to_java}}
        run: |
          PROJ="$(echo "$REF" | \
            sed -E 's|^refs/tags/([^/]*)/.*|\1|')"
          if [ "$PROJ" == "$ROOT_PROJ_NAME" ]; then
            PROJ_PATH="$PATH_TO_JAVA"
          else
            PROJ_PATH="$PATH_TO_JAVA/$PROJ"
          fi;
          echo "PROJ_PATH=$PROJ_PATH"
          [ -d "$PROJ_PATH" ]
          echo "::set-output name=path::$PROJ_PATH"

      - uses: actions/setup-java@v2.5.0
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Auth to GitHub Maven
        env:
          MVN_SETTIGNS: ${{inputs.path_to_mvn_settings}}
        run: |
          if [ -f "$MVN_SETTINGS" ]; then
            cp "$MVN_SETTINGS" ~/.m2/settings.xml
          fi

      - name: Verify version
        env:
          PROJ_PATH: ${{steps.proj.outputs.path}}
          REF: ${{github.ref}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GHCR_R_PAT: ${{ secrets.GHCR_R_PAT }}
        run: |
          cd "$PROJ_PATH"
          VER="$(echo "$REF" | \
            sed -E 's|^refs/tags/[^/]*/(.*)|\1|' | \
            sed -E 's|/|.|g')"
          echo "VER=$VER"
          MVN_VER="$(mvn help:evaluate -Dexpression=project.version -pl . --non-recursive -q -DforceStdout)"
          echo "MVN_VER=$MVN_VER"
          [ "$VER" == "$MVN_VER" ]
        #          echo "VER=$VER" >> "$GITHUB_ENV"

    outputs:
      path: ${{steps.proj.outputs.path}}

