name: Deploy to registry
on:
  push:
    tags:
      - commons/**
      - checkerframework-run-pom/**
      - checkerframework-stubs-nullness/**
      - checkerframework-stubs-purity/**
      - checkerframework-stubs-units/**
      - checkerframework-units/**

#env:
#  MVN_EVJ_PATH: ~/.m2/repository/net/evoja

jobs:
  attributes:
    name: Check module name and version
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Verify module
        id: proj
        run: |
          echo ${{github.repository}}/.github/workflows/ca.yaml@${{github.sha}}
          PROJ=$(echo '${{github.ref}}' | \
            sed -E 's|^refs/tags/([^/]*)/.*|\1|')
          if [ $PROJ == 'commons' ]; then
            PROJ_PATH=.
          else
            PROJ_PATH="$PROJ"
          fi;
          echo "PROJ_PATH=$PROJ_PATH"
          [ -d $PROJ_PATH ]
          echo "::set-output name=path::$PROJ_PATH"

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Verify version
        run: |
          cd ${{steps.proj.outputs.path}}
          VER=$(echo '${{github.ref}}' | \
            sed -E 's|^refs/tags/[^/]*/(.*)|\1|' | \
            sed -E 's|/|.|g')
          echo "VER=$VER"
          MVN_VER=$(mvn help:evaluate -Dexpression=project.version -pl . --non-recursive -q -DforceStdout)
          echo "MVN_VER=$MVN_VER"
          [ $VER == $MVN_VER ]
#          echo "VER=$VER" >> $GITHUB_ENV
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    outputs:
      path: ${{steps.proj.outputs.path}}


  ca:
    needs: attributes
    uses: evoja/java-commons/.github/workflows/ca.yaml@f5240ae18aeb9ad6fd2db25c60bb79010b6c5b7b # same as @wf/ca/01

  deploy:
    needs: [attributes,ca]
    runs-on: ubuntu-latest
    env:
      PROJ_PATH: ${{needs.attributes.outputs.path}}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Use cache
        id: cache
        uses: actions/cache@v2
        with:
          key: mvndeps-one-${{hashFiles(format('{0}/pom.xml', env.PROJ_PATH))}}
          restore-keys: |
            mvndeps-all-${{ hashFiles('**/pom.xml') }}
            mvndeps-all-
            mvndeps-one-
            mvndeps-
          path: |
            ~/.m2/repository

      - name: Show Maven and Java versions
        run: |
          echo "### Java"
          java -version
          echo "JAVA_HOME=$JAVA_HOME"
          printf "\n### Maven\n"
          mvn --version

      - name: Build and deploy
        run: |
          cd $PROJ_PATH
          mvn --batch-mode deploy -P purity-strict -pl .
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Print test reports
        run: |
          find . -type d  -name surefire-reports -exec sh -c "echo "==============================================================================="  && echo {} && cat {}/*.txt" \;

      - name: Delete our jars before caching maven dependencies
        run: |
          rm -rf ~/.m2/repository/net/evoja
