name: Deploy to registry
on:
  push:
    tags:
      - common-pom/**
      - checkerframework-run-pom/**
      - checkerframework-stubs-nullness/**
      - checkerframework-stubs-purity/**
      - checkerframework-stubs-units/**
      - checkerframework-units/**

permissions:
  contents: read
  packages: none

jobs:

  attributes:
    name: Check module name and version
    uses: evoja/java-commons/.github/workflows/mvn-attributes.yaml@8bcc189ffa08b29497fcf64f486e27acc89e90ee # same as @wf/mvn-attributes/05
    with:
      java_version: '11'

  editorconfig-checker:
    name: ec
    needs: attributes
    uses: evoja/java-commons/.github/workflows/editorconfig-checker.yaml@8bcc189ffa08b29497fcf64f486e27acc89e90ee # same as @wf/editorconfig-checker/04

  ca-java:
    name: caj
    needs: attributes
    uses: evoja/java-commons/.github/workflows/ca-java.yaml@8bcc189ffa08b29497fcf64f486e27acc89e90ee # same as @wf/ca-java/03
    with:
      java_version: '11'

  deploy-java:
    name: dj
    needs: [attributes, editorconfig-checker, ca-java]
    uses: evoja/java-commons/.github/workflows/deploy-java.yaml@8bcc189ffa08b29497fcf64f486e27acc89e90ee # same as @wf/deploy-java/03
    with:
      path_to_module: ${{needs.attributes.outputs.path}}
      java_version: '11'
    permissions:
      contents: read
      packages: write

